--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/FlowyProject/Flowy
build-by-default: true
branches:
- master
projects:
  ListenExample:
    path: examples/ListenExample/
  Flowy:
    path: flowy/
    model: virion
    type: library
...
