--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/FlowyProject/Flowy
build-by-default: true
branches:
- master
projects:
  Flowy:
    path: flowy/
    model: virion
    type: library
  ListenExample:
    path: examples/ListenExample/
    libs:
      - src: Flowy
  Standard:
    path: standard/
    model: virion
    type: library
...
